In [1]:
import torch

In [2]:
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
  print(f'Gpu is availabe {torch.cuda.get_device_name()}')
else:
  print('Gpu is not available')


Gpu is availabe Tesla T4


In [4]:
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
a, type(a)

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Tensor)

In [5]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [6]:
torch.full((3, 4), 5)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

In [7]:
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [8]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [9]:
torch.manual_seed(42)
a = torch.rand(2, 3)
a

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [10]:
torch.zeros((2, 4)), torch.ones((2, 4))

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [11]:
x = torch.tensor([
   [[1, 2, 3],
    [2, 3, 4]],
   [[1, 2, 3],
    [2, 3, 4]],
])
x.shape

torch.Size([2, 2, 3])

In [12]:
y = torch.ones_like(x)
y

tensor([[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]])

In [13]:
torch.rand_like(x, dtype=torch.float)

tensor([[[0.2566, 0.7936, 0.9408],
         [0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739]]])

In [14]:
x.dtype

torch.int64

In [15]:
y = x.to(torch.float16)
y

tensor([[[1., 2., 3.],
         [2., 3., 4.]],

        [[1., 2., 3.],
         [2., 3., 4.]]], dtype=torch.float16)

In [16]:
x.dtype, y.dtype

(torch.int64, torch.float16)

In [17]:
x = torch.tensor([[2, 4], [7, 8]])
x + 2, x * 2, x / 2, x // 2, x % 5, x ** 2

(tensor([[ 4,  6],
         [ 9, 10]]),
 tensor([[ 4,  8],
         [14, 16]]),
 tensor([[1.0000, 2.0000],
         [3.5000, 4.0000]]),
 tensor([[1, 2],
         [3, 4]]),
 tensor([[2, 4],
         [2, 3]]),
 tensor([[ 4, 16],
         [49, 64]]))

In [18]:
x + torch.eye(2)

tensor([[3., 4.],
        [7., 9.]])

In [19]:
x * torch.tensor([3, 2])

tensor([[ 6,  8],
        [21, 16]])

In [20]:
x @ torch.tensor([3, 2])

tensor([14, 37])

In [21]:
x = torch.randint(1, 10, (3, 3), dtype=torch.float)
x

tensor([[4., 5., 5.],
        [9., 2., 6.],
        [9., 5., 3.]])

In [22]:
x.sum(), x.sum(dim=0), x.sum(dim=1)

(tensor(48.), tensor([22., 12., 14.]), tensor([14., 17., 17.]))

In [23]:
torch.sum(x), torch.sum(x, dim=0), torch.sum(x, dim=1)

(tensor(48.), tensor([22., 12., 14.]), tensor([14., 17., 17.]))

In [24]:
torch.mean(x), torch.mean(x, dim=0), torch.mean(x, dim=1)

(tensor(5.3333),
 tensor([7.3333, 4.0000, 4.6667]),
 tensor([4.6667, 5.6667, 5.6667]))

In [25]:
arr = torch.randint(-5, 10, (5, ))
arr, torch.argmax(arr), torch.argmin(arr)

(tensor([ 4,  2, -1,  7, -5]), tensor(3), tensor(4))

In [26]:
a = torch.tensor([
    [1, 2],
    [3, 4]
])
b = torch.tensor([
    [1, 3],
    [4, 3]
])

a * b, torch.matmul(a, b), a @ b

(tensor([[ 1,  6],
         [12, 12]]),
 tensor([[ 9,  9],
         [19, 21]]),
 tensor([[ 9,  9],
         [19, 21]]))

In [27]:
mat = torch.randint(1, 10, (3, 3), dtype=torch.float)
mat

tensor([[8., 8., 9.],
        [8., 3., 6.],
        [2., 4., 3.]])

In [28]:
torch.transpose(mat, 0, 1)

tensor([[8., 8., 2.],
        [8., 3., 4.],
        [9., 6., 3.]])

In [29]:
torch.det(mat)

tensor(18.0000)

In [30]:
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
b = torch.tensor([
    [1, 4, 2],
    [5, 3, 2],
    [1, 1, 3]
])
a > b, a != b, a < b, a == b

(tensor([[False, False,  True],
         [False,  True,  True],
         [ True,  True,  True]]),
 tensor([[False,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]),
 tensor([[False,  True, False],
         [ True, False, False],
         [False, False, False]]),
 tensor([[ True, False, False],
         [False, False, False],
         [False, False, False]]))

In [31]:
torch.cuda.is_available()

True

In [32]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [38]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [40]:
b = torch.tensor([1, 2, 4], device=device)
b

tensor([1, 2, 4], device='cuda:0')

In [41]:
c = a.to(device)
c

tensor([1, 2, 3], device='cuda:0')

In [50]:
# check difference between tensor on cpu vs tensors on gpu
import time

size = 10000
a = torch.rand(size, size)
b = torch.rand(size, size)
start_time = time.time()
prod = a @ b
end_time = time.time()
cpu_time = end_time - start_time

print(f'Time taken by cpu {cpu_time} seconds')

Time taken by cpu 27.31231141090393 seconds


In [70]:
a = torch.rand(size, size, device=device)
b = torch.rand(size, size, device=device)

start_time = time.time()
prod = a @ b
end_time = time.time()
gpu_time = end_time - start_time

print(f'Time taken by gpu {gpu_time} seconds')

print(f'gpu is {torch.ceil(torch.tensor([cpu_time / gpu_time]))[0]} times faster than cpu')

Time taken by gpu 0.0003058910369873047 seconds
gpu is 89288.0 times faster than cpu


In [79]:
a = torch.rand((4,))
print(a)
a = a.reshape((-1, 1))
print(a)

tensor([0.1952, 0.5085, 0.1602, 0.0169])
tensor([[0.1952],
        [0.5085],
        [0.1602],
        [0.0169]])


In [81]:
import numpy as np

In [82]:
arr = np.array([4, 5, 6])
arr

array([4, 5, 6])

In [83]:
tch = torch.tensor([4, 5, 6])
tch

tensor([4, 5, 6])

In [84]:
b = tch.numpy()
b

array([4, 5, 6])

In [85]:
c = torch.from_numpy(arr)
c

tensor([4, 5, 6])