In [1]:
import torch as tc
import numpy as np

In [2]:
x = tc.tensor(3, dtype=tc.float, requires_grad=True)
y = x**2
y.backward()
x.grad

tensor(6.)

In [3]:
x = tc.tensor(3, dtype=tc.float, requires_grad=True)
y = x ** 2
z = tc.sin(y)
z.backward()
x.grad

tensor(-5.4668)

In [4]:
x, y, z

(tensor(3., requires_grad=True),
 tensor(9., grad_fn=<PowBackward0>),
 tensor(0.4121, grad_fn=<SinBackward0>))

In [5]:
# do by this method
def dz_dx(x):
  return 2 * x * tc.cos(x ** 2)
dz_dx(x)

tensor(-5.4668, grad_fn=<MulBackward0>)

In [6]:
def binary_cross_entropy(y_pred, y):
  return -y * tc.log(y_pred) - (1 - y) * tc.log(1 - y_pred)

In [7]:
x = tc.tensor(6.7)
y = tc.tensor(0.0)

w = tc.tensor(1, dtype=tc.float, requires_grad=True)
b = tc.tensor(0, dtype=tc.float, requires_grad=True)

z = w * x + b
print(z)

y_pred = tc.sigmoid(z)
print(y_pred)
loss = binary_cross_entropy(y_pred, y)

print(loss)
loss.backward()
w.grad, b.grad

tensor(6.7000, grad_fn=<AddBackward0>)
tensor(0.9988, grad_fn=<SigmoidBackward0>)
tensor(6.7012, grad_fn=<SubBackward0>)


(tensor(6.6918), tensor(0.9988))

In [8]:
x = tc.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = (x ** 2).mean()

y.backward()
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [9]:
# problem with the accumulation of gradients
x = tc.tensor(4.0, requires_grad=True)

In [10]:
# run this cell 4 times, you will get to know gradients accumulates and we will not get correct result

y = (x ** 2)
print(y)
y.backward()
x.grad

tensor(16., grad_fn=<PowBackward0>)


tensor(8.)

In [11]:
# either use clear grad

y = (x ** 2)
y.backward()
print(x.grad)
x.grad.zero_()

tensor(16.)


tensor(0.)

### close gradient tracking

In [22]:
x = tc.tensor([1, 2, 3], dtype=tc.float, requires_grad=True)
y = (x ** 2).mean()
y.backward()
x.grad, x

(tensor([0.6667, 1.3333, 2.0000]), tensor([1., 2., 3.], requires_grad=True))

In [24]:
# Method 1
x.requires_grad_(False)
x.grad, x

(tensor([0.6667, 1.3333, 2.0000]), tensor([1., 2., 3.]))

In [25]:
# Method 2
x = tc.tensor([1, 2, 3], dtype=tc.float, requires_grad=True)
p = x.detach_()
p

tensor([1., 2., 3.])

In [28]:
# Method 3
x = tc.tensor([1, 2, 3], dtype=tc.float, requires_grad=True)
with tc.no_grad():
  y = (x ** 2).mean()
y

tensor(4.6667)