In [38]:
import torch
import torch.nn as nn
import numpy as np

## BASIC SINGLE NEURON MODEL

In [39]:
class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    z = self.linear(x)
    y_pred = self.sigmoid(z)
    return y_pred

In [40]:
features = torch.rand(10, 5)
model = Model(features.shape[1])
# model.forward(features)

# standard way uses Magic method __call__()
model(features)

tensor([[0.5269],
        [0.4063],
        [0.4923],
        [0.4427],
        [0.4046],
        [0.4381],
        [0.3955],
        [0.4899],
        [0.5184],
        [0.4536]], grad_fn=<SigmoidBackward0>)

In [41]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[ 0.0026,  0.3077,  0.4087, -0.4060, -0.2869]], requires_grad=True),
 Parameter containing:
 tensor([-0.1200], requires_grad=True))

In [42]:
!pip install torchinfo

In [43]:
from torchinfo import summary
summary(model, (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## 2 LAYER NN

In [44]:
class Model2(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    z = self.linear(x)
    z = self.relu(z)
    z = self.linear2(z)
    y_pred = self.sigmoid(z)
    return y_pred

In [45]:
features = torch.rand(10, 5)
model = Model2(features.shape[1])
model(features)

tensor([[0.4766],
        [0.4519],
        [0.4618],
        [0.4500],
        [0.4648],
        [0.4740],
        [0.4564],
        [0.4826],
        [0.4484],
        [0.4861]], grad_fn=<SigmoidBackward0>)

In [46]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[-0.0135,  0.0083, -0.0320,  0.3296, -0.3521],
         [-0.0449, -0.2936,  0.4354,  0.2370, -0.1369],
         [-0.2495,  0.1216,  0.3438,  0.1015, -0.2063]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2044, -0.3868,  0.1513], requires_grad=True))

In [47]:
model.linear2.weight, model.linear2.bias

(Parameter containing:
 tensor([[ 0.3888, -0.4243,  0.0310]], requires_grad=True),
 Parameter containing:
 tensor([-0.2149], requires_grad=True))

In [48]:
summary(model, features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## SEQUENTIAL CONTAINERS


In [50]:
class Model3(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, x):
    y_pred = self.network(x)
    return y_pred

In [51]:
data = torch.rand(10, 5)
model = Model3(data.shape[1])
model(data)

tensor([[0.5854],
        [0.5683],
        [0.6157],
        [0.6236],
        [0.6075],
        [0.6155],
        [0.6295],
        [0.5306],
        [0.6012],
        [0.5947]], grad_fn=<SigmoidBackward0>)

In [61]:
for idx, layer in enumerate(model.network):
  if isinstance(layer, nn.Linear):
    print(f"Layer {idx}: {layer}, \n weight: {layer.weight}")
  else:
    print(f"Layer {idx}: {layer}")

Layer 0: Linear(in_features=5, out_features=3, bias=True), 
 weight: Parameter containing:
tensor([[ 0.0239,  0.3781,  0.2996, -0.0584,  0.3363],
        [-0.1512,  0.0020, -0.0729,  0.3896, -0.2260],
        [ 0.3484, -0.2006, -0.1591, -0.2556,  0.3157]], requires_grad=True)
Layer 1: ReLU()
Layer 2: Linear(in_features=3, out_features=1, bias=True), 
 weight: Parameter containing:
tensor([[ 0.2291,  0.5698, -0.5039]], requires_grad=True)
Layer 3: Sigmoid()


In [53]:
summary(model, data.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model3                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00